/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synjones_bluetooth_DecodeWlt */

#ifndef _Included_com_synjones_bluetooth_DecodeWlt
#define _Included_com_synjones_bluetooth_DecodeWlt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synjones_bluetooth_DecodeWlt
 * Method:    Wlt2Bmp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_synjones_bluetooth_DecodeWlt_Wlt2Bmp
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
